apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: quickstart
spec:
  version: 7.7.0
  count: 1
  config:
    apm-server.rum.enabled: true
    apm-server.rum.event_rate.limit: 300
    apm-server.rum.event_rate.lru_size: 1000
    apm-server.rum.allow_origins: ['*']
    apm-server.jaeger.http.enabled: true
    # apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.http.host: 0.0.0.0:14268
    # apm-server.jaeger.grpc.host: 0.0.0.0:14250
  elasticsearchRef:
    name: "quickstart"
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - name: apm
            port: 8200
            targetPort: 8200
          - name: http
            port: 14268
            targetPort: 14268
          - name: grpc
            port: 14250
            targetPort: 14250
