apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.7.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
      node.store.allow_mmap: false
      xpack.monitoring.collection.enabled: false
      # Enabling trial license
      xpack.license.self_generated.type: trial
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
        annotations:
          co.elastic.logs/module: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
  # http:
  #   service:
  #     spec:
  #       type: LoadBalancer
