---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-init-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat-init
data:
  metricbeat.yml: |-
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    metricbeat.modules:
      - module: nginx
      - module: kubernetes
      - module: docker
      - module: system
      - module: mysql
      - module: prometheus
      - module: elasticsearch
      - module: elasticsearch-xpack
      - module: kibana

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    # This part is only required with ECK-based Elastic cluster
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.verification_mode: none
    setup.kibana:
      host: ${KIBANA_HOST}
      ssl.verification_mode: none
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metricbeat-init
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: metricbeat-init
        image: docker.elastic.co/beats/metricbeat:7.7.0
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "setup"
        ]
        env:

        # This section is for connecting to Elastic cluster running through ECK
        #  in the default namespace. Uncomment this section and comment out the
        # init section with ELASTIC_CLOUD_ID and ELASTIC_CLOUD_AUTH variables
        - name: KIBANA_HOST
          value: "https://quickstart-kb-http.default.svc.cluster.local"
        - name: ELASTICSEARCH_HOST
          value: "https://quickstart-es-http.default.svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eck-secret
              key: elastic-password
        # End of ECK cluster connectivity

        # # This section is for connecting to Elastic Cloud cluster using
        # #  ELASTIC_CLOUD_ID and ELASTIC_CLOUD_AUTH defined through secrets
        # - name: ELASTIC_CLOUD_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloud-secret
        #       key: cloud-id
        # - name: ELASTIC_CLOUD_AUTH
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloud-secret
        #       key: cloud-auth
        # # End of Elastic Cloud connectivity section

        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-init-config
      restartPolicy: Never
  backoffLimit: 0
